import type { Metadata } from "next";
import MainLayout from "@/layouts";
import "./index.scss";

export const metadata: Metadata = {
  title: "Pet Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MainLayout> {children}</MainLayout>
      </body>
    </html>
  );
}
